#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib


sqlplus64 "username/password@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF
SET PAGESIZE 50
SET LINESIZE 200
SET FEEDBACK OFF
SET HEADING ON
SET TRIMSPOOL ON
SET WRAP OFF

COLUMN LICENSE_NUMBER FORMAT A12
COLUMN FIRST_NAME FORMAT A15
COLUMN MIDDLE_NAME FORMAT A5
COLUMN LAST_NAME FORMAT A15
COLUMN DATE_OF_B FORMAT A10
COLUMN APARTMENT FORMAT A10
COLUMN COUNTRY FORMAT A10
COLUMN CITY FORMAT A10
COLUMN PROVINCE FORMAT A15
COLUMN POSTAL_COD FORMAT A8
COLUMN STREET_ADDRESS FORMAT A25
COLUMN EMAIL_ADDRESS FORMAT A30
COLUMN PHONE_NUMBER FORMAT A12

COLUMN LOCATION_NUMBER FORMAT 9999
COLUMN LOCATION_NAME FORMAT A3

select * FROM location;
select * FROM customer;
select * FROM employees;
select * FROM model;
select * FROM car;
select * FROM reservation;
select * FROM billing;
select * FROM protections_coverages;








EXIT;
