SET DEFINE OFF

INSERT INTO LOCATION (LOCATION_NUMBER, LOCATION_NAME, PHONE_NUMBER, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS) 
VALUES (1, 'CTOQ', '416-123-1234', 'Canada', 'Toronto', 'Ontario', 'M5A1A1', '123 Queen St W');

INSERT INTO LOCATION (LOCATION_NUMBER, LOCATION_NAME, PHONE_NUMBER, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS) 
VALUES (2, 'CTOK', '416-123-5678', 'Canada', 'Toronto', 'Ontario', 'M5B2B2', '456 King St E');

INSERT INTO LOCATION (LOCATION_NUMBER, LOCATION_NAME, PHONE_NUMBER, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS) 
VALUES (3, 'CMOL', '416-321-1234', 'Canada', 'Mississauga', 'Ontario', 'L5M3C3', '789 Lakeshore Blvd');

INSERT INTO LOCATION (LOCATION_NUMBER, LOCATION_NAME, PHONE_NUMBER, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS) 
VALUES (4, 'CCAM', '647-321-1234', 'Canada', 'Calgary', 'Alberta', 'T2P4P4', '101 Mountain Rd');

INSERT INTO LOCATION (LOCATION_NUMBER, LOCATION_NAME, PHONE_NUMBER, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS) 
VALUES (5, 'CVBCO', '647-123-5678', 'Canada', 'Vancouver', 'British Columbia', 'V6B5B5', '112 Ocean Blvd');

INSERT INTO LOCATION (LOCATION_NUMBER, LOCATION_NAME, PHONE_NUMBER, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS) 
VALUES (6, 'CCED', '780-987-6543', 'Canada', 'Edmonton', 'Alberta', 'T5J2T2', '150 Jasper Ave NW');

INSERT INTO LOCATION (LOCATION_NUMBER, LOCATION_NAME, PHONE_NUMBER, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS) 
VALUES (7, 'CMON', '514-321-4321', 'Canada', 'Montreal', 'Quebec', 'H3B3B3', '200 Saint Catherine St W');

INSERT INTO LOCATION (LOCATION_NUMBER, LOCATION_NAME, PHONE_NUMBER, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS) 
VALUES (8, 'COOW', '613-567-4321', 'Canada', 'Ottawa', 'Ontario', 'K1A1A1', '350 Wellington St');

INSERT INTO LOCATION (LOCATION_NUMBER, LOCATION_NAME, PHONE_NUMBER, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS) 
VALUES (9, 'CHFC', '902-987-1234', 'Canada', 'Halifax', 'Nova Scotia', 'B3J3J3', '99 Barrington St');

INSERT INTO LOCATION (LOCATION_NUMBER, LOCATION_NAME, PHONE_NUMBER, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS) 
VALUES (10, 'CWPG', '204-654-3210', 'Canada', 'Winnipeg', 'Manitoba', 'R3C2C2', '250 Portage Ave');

INSERT INTO LOCATION (LOCATION_NUMBER, LOCATION_NAME, PHONE_NUMBER, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS) 
VALUES (11, 'CSRJ', '506-234-5678', 'Canada', 'Saint John', 'New Brunswick', 'E2L1A1', '60 King St');

INSERT INTO LOCATION (LOCATION_NUMBER, LOCATION_NAME, PHONE_NUMBER, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS) 
VALUES (12, 'CLDN', '807-876-5432', 'Canada', 'London', 'Ontario', 'N6A5B6', '175 Dundas St');

INSERT INTO LOCATION (LOCATION_NUMBER, LOCATION_NAME, PHONE_NUMBER, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS) 
VALUES (13, 'CSOU', '705-654-7890', 'Canada', 'Sudbury', 'Ontario', 'P3E1C8', '400 Elm St');

INSERT INTO LOCATION (LOCATION_NUMBER, LOCATION_NAME, PHONE_NUMBER, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS) 
VALUES (14, 'CCQG', '418-321-5678', 'Canada', 'Quebec City', 'Quebec', 'G1R1R1', '500 Grande AllÃ©e E');

INSERT INTO LOCATION (LOCATION_NUMBER, LOCATION_NAME, PHONE_NUMBER, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS) 
VALUES (15, 'CWDS', '867-987-6543', 'Canada', 'Whitehorse', 'Yukon', 'Y1A1A1', '700 Main St');


INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2001, 1, 'Alan', 'B.', 'Richards', 55000, 'Manager', to_date('02/17/1985', 'MM/DD/RRRR'), '416-555-1212', 'alan.richards@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2002, 2, 'Samantha', 'C.', 'Blake', 45000, 'Janitor', to_date('07/25/1990', 'MM/DD/RRRR'), '416-555-2323', 'samantha.blake@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2003, 3, 'Peter', 'D.', 'Jones', 60000, 'Manager', to_date('12/10/1983', 'MM/DD/RRRR'), '416-555-3434', 'peter.jones@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2004, 4, 'Jessica', 'E.', 'Roberts', 52000, 'Assistant', to_date('04/04/1995', 'MM/DD/RRRR'), '403-555-4545', 'jessica.roberts@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2005, 5, 'Ryan', 'F.', 'Stewart', 48000, 'Salesperson', to_date('04/04/1995', 'MM/DD/RRRR'), '403-555-4545', 'ryan.stewart@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2006, 1, 'Daniel', 'A.', 'Smith', 60000, 'Manager', to_date('01/15/1988', 'MM/DD/RRRR'), '416-555-1616', 'daniel.smith@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2007, 2, 'Emily', 'B.', 'Johnson', 38000, 'Janitor', to_date('03/22/1995', 'MM/DD/RRRR'), '416-555-1717', 'emily.johnson@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2008, 3, 'Matthew', 'C.', 'Williams', 55000, 'Manager', to_date('05/30/1984', 'MM/DD/RRRR'), '416-555-1818', 'matthew.williams@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2009, 4, 'Olivia', 'D.', 'Jones', 49000, 'Assistant', to_date('07/14/1992', 'MM/DD/RRRR'), '403-555-1919', 'olivia.jones@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2010, 5, 'Lucas', 'E.', 'Brown', 45000, 'Salesperson', to_date('08/19/1989', 'MM/DD/RRRR'), '403-555-2020', 'lucas.brown@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2011, 1, 'Sophia', 'F.', 'Davis', 67000, 'Manager', to_date('12/01/1990', 'MM/DD/RRRR'), '416-555-2121', 'sophia.davis@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2012, 2, 'James', 'G.', 'Miller', 42000, 'Janitor', to_date('06/05/1996', 'MM/DD/RRRR'), '416-555-2222', 'james.miller@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2013, 3, 'Ava', 'H.', 'Garcia', 63000, 'Manager', to_date('11/25/1982', 'MM/DD/RRRR'), '416-555-2323', 'ava.garcia@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2014, 4, 'Charlotte', 'I.', 'Martinez', 52000, 'Assistant', to_date('09/15/1993', 'MM/DD/RRRR'), '403-555-2424', 'charlotte.martinez@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2015, 5, 'Noah', 'J.', 'Hernandez', 46000, 'Salesperson', to_date('02/27/1985', 'MM/DD/RRRR'), '403-555-2525', 'noah.hernandez@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2016, 1, 'Amelia', 'K.', 'Lopez', 58000, 'Manager', to_date('04/18/1981', 'MM/DD/RRRR'), '416-555-2626', 'amelia.lopez@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2017, 2, 'Elijah', 'L.', 'Gonzalez', 37000, 'Janitor', to_date('08/22/1998', 'MM/DD/RRRR'), '416-555-2727', 'elijah.gonzalez@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2018, 3, 'Harper', 'M.', 'Wilson', 59000, 'Manager', to_date('03/16/1986', 'MM/DD/RRRR'), '416-555-2828', 'harper.wilson@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2019, 4, 'Jack', 'N.', 'Anderson', 50000, 'Assistant', to_date('05/05/1994', 'MM/DD/RRRR'), '403-555-2929', 'jack.anderson@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2020, 5, 'Grace', 'O.', 'Thomas', 48000, 'Salesperson', to_date('11/12/1990', 'MM/DD/RRRR'), '403-555-3030', 'grace.thomas@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2021, 1, 'Ethan', 'P.', 'Taylor', 64000, 'Manager', to_date('12/30/1987', 'MM/DD/RRRR'), '416-555-3131', 'ethan.taylor@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2022, 2, 'Chloe', 'Q.', 'Moore', 43000, 'Janitor', to_date('02/24/1999', 'MM/DD/RRRR'), '416-555-3232', 'chloe.moore@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2023, 3, 'Mason', 'R.', 'Jackson', 61000, 'Manager', to_date('07/19/1983', 'MM/DD/RRRR'), '416-555-3333', 'mason.jackson@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2024, 4, 'Zoe', 'S.', 'Martin', 52000, 'Assistant', to_date('01/10/1992', 'MM/DD/RRRR'), '403-555-3434', 'zoe.martin@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2025, 5, 'Liam', 'T.', 'Lee', 46000, 'Salesperson', to_date('04/28/1989', 'MM/DD/RRRR'), '403-555-3535', 'liam.lee@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2026, 1, 'Lily', 'U.', 'Perez', 60000, 'Manager', to_date('05/02/1984', 'MM/DD/RRRR'), '416-555-3636', 'lily.perez@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2027, 2, 'Alexander', 'V.', 'Thompson', 38000, 'Janitor', to_date('09/15/1996', 'MM/DD/RRRR'), '416-555-3737', 'alexander.thompson@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2028, 3, 'Sofia', 'W.', 'White', 67000, 'Manager', to_date('08/08/1982', 'MM/DD/RRRR'), '416-555-3838', 'sofia.white@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2029, 4, 'Matthew', 'X.', 'Harris', 53000, 'Assistant', to_date('03/20/1990', 'MM/DD/RRRR'), '403-555-3939', 'matthew.harris@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2030, 5, 'Victoria', 'Y.', 'Clark', 48000, 'Salesperson', to_date('11/23/1986', 'MM/DD/RRRR'), '403-555-4040', 'victoria.clark@driveease.com');


INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M12345', 'Mickey', 'T.', 'Mouse', to_date('07/10/1985', 'MM/DD/YYYY'), 'Apt 101', 'Canada', 'Toronto', 'Ontario', 'M5A1A1', '213 Queen St W', 'mickey.m@gmail.com', '416-123-1111');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M6789', 'Minnie', 'E.', 'Mouse', to_date('03/22/1990', 'MM/DD/YYYY'), 'Apt 101', 'Canada', 'Toronto', 'Ontario', 'M5B2B2', '213 Queen St W', 'minnie.m@gmail.com', '416-123-2222');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M34567', 'Joanne', NULL, 'Mills', to_date('11/18/1982', 'MM/DD/YYYY'), NULL, 'Canada', 'Mississauga', 'Ontario', 'L5M3C3', '800 Lakeshore Blvd', 'jm@gmail.com', '647-321-3333');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('J45678', 'Brandon', 'J.', 'Jones', to_date('05/30/1995', 'MM/DD/YYYY'), NULL, 'Canada', 'Calgary', 'Alberta', 'T2P4P4', '180 Mountain Rd', 'b.jones@yahoo.ca', '403-555-4444');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('B56789', 'Gabriellel', 'D.', 'Brown', to_date('08/15/1987', 'MM/DD/YYYY'), 'Unit 12B', 'Canada', 'Vancouver', 'British Columbia', 'V6B5B5', '292 Country Rd', 'g.brown@gmail.com', '647-123-5282');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10001', 'Oliver', 'A.', 'Smith', to_date('01/01/1980', 'MM/DD/YYYY'), 'Apt 1', 'Canada', 'Toronto', 'Ontario', 'M5A1A2', '1 Main St', 'oliver.smith@gmail.com', '416-123-0001');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10002', 'Sophia', 'B.', 'Johnson', to_date('02/12/1985', 'MM/DD/YYYY'), 'Apt 2', 'Canada', 'Toronto', 'Ontario', 'M5A1A3', '2 Main St', 'sophia.j@gmail.com', '416-123-0002');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10003', 'Liam', 'C.', 'Williams', to_date('03/14/1992', 'MM/DD/YYYY'), 'Apt 3', 'Canada', 'Toronto', 'Ontario', 'M5A1A4', '3 Main St', 'liam.williams@gmail.com', '416-123-0003');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10004', 'Emma', 'D.', 'Jones', to_date('04/22/1988', 'MM/DD/YYYY'), 'Apt 4', 'Canada', 'Toronto', 'Ontario', 'M5A1A5', '4 Main St', 'emma.jones@gmail.com', '416-123-0004');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10005', 'Noah', 'E.', 'Garcia', to_date('05/19/1990', 'MM/DD/YYYY'), 'Apt 5', 'Canada', 'Toronto', 'Ontario', 'M5A1A6', '5 Main St', 'noah.garcia@gmail.com', '416-123-0005');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10006', 'Ava', 'F.', 'Martinez', to_date('06/11/1995', 'MM/DD/YYYY'), 'Apt 6', 'Canada', 'Toronto', 'Ontario', 'M5A1A7', '6 Main St', 'ava.martinez@gmail.com', '416-123-0006');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10007', 'Isabella', 'G.', 'Davis', to_date('07/27/1982', 'MM/DD/YYYY'), 'Apt 7', 'Canada', 'Toronto', 'Ontario', 'M5A1A8', '7 Main St', 'isabella.davis@gmail.com', '416-123-0007');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10008', 'Mason', 'H.', 'Rodriguez', to_date('08/15/1994', 'MM/DD/YYYY'), 'Apt 8', 'Canada', 'Toronto', 'Ontario', 'M5A1A9', '8 Main St', 'mason.rodriguez@gmail.com', '416-123-0008');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10009', 'James', 'I.', 'Martinez', to_date('09/09/1980', 'MM/DD/YYYY'), 'Apt 9', 'Canada', 'Toronto', 'Ontario', 'M5A1B1', '9 Main St', 'james.martinez@gmail.com', '416-123-0009');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10010', 'Charlotte', 'J.', 'Hernandez', to_date('10/14/1991', 'MM/DD/YYYY'), 'Apt 10', 'Canada', 'Toronto', 'Ontario', 'M5A1B2', '10 Main St', 'charlotte.hernandez@gmail.com', '416-123-0010');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10011', 'Elijah', 'K.', 'Lopez', to_date('11/02/1993', 'MM/DD/YYYY'), 'Apt 11', 'Canada', 'Toronto', 'Ontario', 'M5A1B3', '11 Main St', 'elijah.lopez@gmail.com', '416-123-0011');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10012', 'Amelia', 'L.', 'Gonzalez', to_date('12/29/1986', 'MM/DD/YYYY'), 'Apt 12', 'Canada', 'Toronto', 'Ontario', 'M5A1B4', '12 Main St', 'amelia.gonzalez@gmail.com', '416-123-0012');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10013', 'Benjamin', 'M.', 'Wilson', to_date('01/22/1990', 'MM/DD/YYYY'), 'Apt 13', 'Canada', 'Toronto', 'Ontario', 'M5A1B5', '13 Main St', 'benjamin.wilson@gmail.com', '416-123-0013');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10014', 'Harper', 'N.', 'Anderson', to_date('02/20/1988', 'MM/DD/YYYY'), 'Apt 14', 'Canada', 'Toronto', 'Ontario', 'M5A1B6', '14 Main St', 'harper.anderson@gmail.com', '416-123-0014');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10015', 'Lucas', 'O.', 'Thomas', to_date('03/13/1992', 'MM/DD/YYYY'), 'Apt 15', 'Canada', 'Toronto', 'Ontario', 'M5A1B7', '15 Main St', 'lucas.thomas@gmail.com', '416-123-0015');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10016', 'Evelyn', 'P.', 'Taylor', to_date('04/05/1994', 'MM/DD/YYYY'), 'Apt 16', 'Canada', 'Toronto', 'Ontario', 'M5A1B8', '16 Main St', 'evelyn.taylor@gmail.com', '416-123-0016');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10017', 'Henry', 'Q.', 'Moore', to_date('05/17/1985', 'MM/DD/YYYY'), 'Apt 17', 'Canada', 'Toronto', 'Ontario', 'M5A1B9', '17 Main St', 'henry.moore@gmail.com', '416-123-0017');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10018', 'Sofia', 'R.', 'Jackson', to_date('06/25/1996', 'MM/DD/YYYY'), 'Apt 18', 'Canada', 'Toronto', 'Ontario', 'M5A1C1', '18 Main St', 'sofia.jackson@gmail.com', '416-123-0018');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10019', 'Alexander', 'S.', 'White', to_date('07/07/1983', 'MM/DD/YYYY'), 'Apt 19', 'Canada', 'Toronto', 'Ontario', 'M5A1C2', '19 Main St', 'alexander.white@gmail.com', '416-123-0019');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10020', 'Grace', 'T.', 'Harris', to_date('08/23/1991', 'MM/DD/YYYY'), 'Apt 20', 'Canada', 'Toronto', 'Ontario', 'M5A1C3', '20 Main St', 'grace.harris@gmail.com', '416-123-0020');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10021', 'Daniel', 'U.', 'Martin', to_date('09/12/1984', 'MM/DD/YYYY'), 'Apt 21', 'Canada', 'Toronto', 'Ontario', 'M5A1C4', '21 Main St', 'daniel.martin@gmail.com', '416-123-0021');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10022', 'Lily', 'V.', 'Thompson', to_date('10/30/1990', 'MM/DD/YYYY'), 'Apt 22', 'Canada', 'Toronto', 'Ontario', 'M5A1C5', '22 Main St', 'lily.thompson@gmail.com', '416-123-0022');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10023', 'Matthew', 'W.', 'Garcia', to_date('11/11/1987', 'MM/DD/YYYY'), 'Apt 23', 'Canada', 'Toronto', 'Ontario', 'M5A1C6', '23 Main St', 'matthew.garcia@gmail.com', '416-123-0023');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10024', 'Zoe', 'X.', 'Martinez', to_date('12/09/1992', 'MM/DD/YYYY'), 'Apt 24', 'Canada', 'Toronto', 'Ontario', 'M5A1C7', '24 Main St', 'zoe.martinez@gmail.com', '416-123-0024');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10025', 'Logan', 'Y.', 'Rodriguez', to_date('01/19/1985', 'MM/DD/YYYY'), 'Apt 25', 'Canada', 'Toronto', 'Ontario', 'M5A1C8', '25 Main St', 'logan.rodriguez@gmail.com', '416-123-0025');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10026', 'Scarlett', 'Z.', 'Perez', to_date('02/25/1993', 'MM/DD/YYYY'), 'Apt 26', 'Canada', 'Toronto', 'Ontario', 'M5A1C9', '26 Main St', 'scarlett.perez@gmail.com', '416-123-0026');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10027', 'Jackson', 'A.', 'Williams', to_date('03/17/1989', 'MM/DD/YYYY'), 'Apt 27', 'Canada', 'Toronto', 'Ontario', 'M5A1D1', '27 Main St', 'jackson.williams@gmail.com', '416-123-0027');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10028', 'Aiden', 'B.', 'Anderson', to_date('04/23/1991', 'MM/DD/YYYY'), 'Apt 28', 'Canada', 'Toronto', 'Ontario', 'M5A1D2', '28 Main St', 'aiden.anderson@gmail.com', '416-123-0028');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10029', 'Evelyn', 'C.', 'Roberts', to_date('05/18/1987', 'MM/DD/YYYY'), 'Apt 29', 'Canada', 'Toronto', 'Ontario', 'M5A1D3', '29 Main St', 'evelyn.roberts@gmail.com', '416-123-0029');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10030', 'Matthew', 'D.', 'Hernandez', to_date('06/30/1994', 'MM/DD/YYYY'), 'Apt 30', 'Canada', 'Toronto', 'Ontario', 'M5A1D4', '30 Main St', 'matthew.hernandez@gmail.com', '416-123-0030');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10031', 'Chloe', 'E.', 'King', to_date('07/21/1993', 'MM/DD/YYYY'), 'Apt 31', 'Canada', 'Toronto', 'Ontario', 'M5A1D5', '31 Main St', 'chloe.king@gmail.com', '416-123-0031');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10032', 'Lucas', 'F.', 'Lee', to_date('08/12/1989', 'MM/DD/YYYY'), 'Apt 32', 'Canada', 'Toronto', 'Ontario', 'M5A1D6', '32 Main St', 'lucas.lee@gmail.com', '416-123-0032');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10033', 'Mia', 'G.', 'Walker', to_date('09/11/1991', 'MM/DD/YYYY'), 'Apt 33', 'Canada', 'Toronto', 'Ontario', 'M5A1D7', '33 Main St', 'mia.walker@gmail.com', '416-123-0033');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10034', 'Noah', 'H.', 'Hall', to_date('10/16/1992', 'MM/DD/YYYY'), 'Apt 34', 'Canada', 'Toronto', 'Ontario', 'M5A1D8', '34 Main St', 'noah.hall@gmail.com', '416-123-0034');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10035', 'Isabella', 'I.', 'Young', to_date('11/20/1996', 'MM/DD/YYYY'), 'Apt 35', 'Canada', 'Toronto', 'Ontario', 'M5A1D9', '35 Main St', 'isabella.young@gmail.com', '416-123-0035');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10036', 'Oliver', 'J.', 'Wright', to_date('12/27/1985', 'MM/DD/YYYY'), 'Apt 36', 'Canada', 'Toronto', 'Ontario', 'M5A1E1', '36 Main St', 'oliver.wright@gmail.com', '416-123-0036');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10037', 'Sofia', 'K.', 'Scott', to_date('01/18/1990', 'MM/DD/YYYY'), 'Apt 37', 'Canada', 'Toronto', 'Ontario', 'M5A1E2', '37 Main St', 'sofia.scott@gmail.com', '416-123-0037');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10038', 'Elijah', 'L.', 'Green', to_date('02/24/1989', 'MM/DD/YYYY'), 'Apt 38', 'Canada', 'Toronto', 'Ontario', 'M5A1E3', '38 Main St', 'elijah.green@gmail.com', '416-123-0038');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10039', 'Amelia', 'M.', 'Adams', to_date('03/09/1991', 'MM/DD/YYYY'), 'Apt 39', 'Canada', 'Toronto', 'Ontario', 'M5A1E4', '39 Main St', 'amelia.adams@gmail.com', '416-123-0039');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10040', 'Benjamin', 'N.', 'Baker', to_date('04/02/1988', 'MM/DD/YYYY'), 'Apt 40', 'Canada', 'Toronto', 'Ontario', 'M5A1E5', '40 Main St', 'benjamin.baker@gmail.com', '416-123-0040');


INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (1, 2020, 'Corolla', 'Toyota', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (2, 2021, 'Civic', 'Honda', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (3, 2022, 'Model 3', 'Tesla', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (4, 2019, 'Mustang', 'Ford', 4);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (5, 2020, 'Cherokee', 'Jeep', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (6, 2018, 'Accord', 'Honda', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (7, 2020, 'Camry', 'Toyota', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (8, 2019, 'Rav4', 'Toyota', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (9, 2022, 'Escape', 'Ford', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (10, 2021, 'Explorer', 'Ford', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (11, 2020, 'Altima', 'Nissan', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (12, 2023, 'Sentra', 'Nissan', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (13, 2021, 'Santa Fe', 'Hyundai', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (14, 2022, 'Tucson', 'Hyundai', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (15, 2020, 'Sorento', 'Kia', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (16, 2021, 'Sportage', 'Kia', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (17, 2019, 'Optima', 'Kia', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (18, 2022, 'Highlander', 'Toyota', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (19, 2023, 'Pathfinder', 'Nissan', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (20, 2020, 'Suburban', 'Chevrolet', 8);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (21, 2021, 'Tahoe', 'Chevrolet', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (22, 2022, 'Impala', 'Chevrolet', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (23, 2018, 'Malibu', 'Chevrolet', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (24, 2023, 'Fusion', 'Ford', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (25, 2021, 'Mazda3', 'Mazda', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (26, 2019, 'Mazda6', 'Mazda', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (27, 2022, 'CX-5', 'Mazda', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (28, 2023, 'CX-9', 'Mazda', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (29, 2020, 'Forester', 'Subaru', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (30, 2021, 'Outback', 'Subaru', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (31, 2022, 'Ascent', 'Subaru', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (32, 2019, 'Wrangler', 'Jeep', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (33, 2020, 'Compass', 'Jeep', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (34, 2021, 'Gladiator', 'Jeep', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (35, 2022, 'Telluride', 'Kia', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (36, 2023, 'Palisade', 'Hyundai', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (37, 2020, 'Atlas', 'Volkswagen', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (38, 2021, 'Tiguan', 'Volkswagen', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (39, 2022, 'Passat', 'Volkswagen', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (40, 2023, 'Jetta', 'Volkswagen', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (41, 2019, 'S-Class', 'Mercedes-Benz', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (42, 2020, 'E-Class', 'Mercedes-Benz', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (43, 2021, 'C-Class', 'Mercedes-Benz', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (44, 2022, 'A4', 'Audi', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (45, 2023, 'Q7', 'Audi', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (46, 2018, 'Q5', 'Audi', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (47, 2020, 'A6', 'Audi', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (48, 2021, 'Q3', 'Audi', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (49, 2022, 'Range Rover', 'Land Rover', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (50, 2023, 'Defender', 'Land Rover', 5);


INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (12346, 1, 6, 1, 12000, 38.5, 9.5, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (67892, 2, 7, 1, 14000, 52, 12.5, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (1113, 3, 8, 0, 11000, 60.75, 13, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (13142, 4, 9, 1, 9000, 80.25, 19, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (51618, 5, 10, 1, 22000, 58.99, 16, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (12347, 1, 11, 1, 15000, 39.99, 10, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (67893, 2, 12, 1, 18500, 51.5, 12.25, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (1114, 3, 13, 0, 14000, 75, 15, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (13143, 4, 14, 1, 6000, 82, 20, 'Sports');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (51619, 5, 15, 1, 25000, 60.99, 17, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (12348, 1, 16, 1, 17000, 42, 10.5, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (67894, 2, 17, 1, 19000, 53.5, 13, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (1115, 3, 18, 0, 10000, 65.99, 14.5, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (13144, 4, 19, 1, 5500, 85.5, 21, 'Sports');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (51620, 5, 20, 1, 23000, 62.99, 18, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (12349, 1, 21, 1, 13000, 43.99, 11, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (67895, 2, 22, 1, 20000, 55, 13.5, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (1116, 3, 23, 0, 9000, 70.5, 16, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (13145, 4, 24, 1, 7500, 88.99, 22.5, 'Sports');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (51621, 5, 25, 1, 26000, 64.5, 19, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (12350, 1, 26, 1, 14500, 45.5, 11.5, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (67896, 2, 27, 1, 21000, 57.99, 14, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (1117, 3, 28, 0, 8000, 80.99, 17.5, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (13146, 4, 29, 1, 7000, 90.5, 23, 'Sports');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (51622, 5, 30, 1, 27000, 66.5, 20, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (12351, 1, 31, 1, 12500, 47, 12, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (67897, 2, 32, 1, 22000, 60, 15, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (1118, 3, 33, 0, 8500, 82.5, 18.5, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (13147, 4, 34, 1, 6200, 92.5, 24, 'Sports');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (51623, 5, 35, 1, 28000, 68.99, 21.5, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (12352, 1, 36, 1, 13500, 48.5, 12.5, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (67898, 2, 37, 1, 23000, 62, 16, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (1119, 3, 38, 0, 9500, 85.99, 19, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (13148, 4, 39, 1, 8000, 95.5, 25, 'Sports');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (51624, 5, 40, 1, 29000, 70.5, 22, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (12353, 1, 41, 1, 16000, 50.5, 13, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (67899, 2, 42, 1, 24000, 64, 17, 'Sedan');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (1120, 3, 43, 0, 10500, 90, 20.5, 'SUV');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (13149, 4, 44, 1, 8500, 98.99, 26, 'Sports');

INSERT INTO CAR (REGISTRATION_NUMBER, LOCATION_NUMBER, MODEL_NUMBER, AVAILABILITY, MILEAGE, RENTAL_PRICE, LATE_FEE, CAR_TYPE) 
VALUES (51625, 5, 45, 1, 30000, 72, 23, 'SUV');


INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (1, 'M12345', 12346, 1, 2, 'Confirmed', to_date('09/20/2024', 'MM/DD/RRRR'), to_date('09/25/2024', 'MM/DD/RRRR'), to_date('09/30/2024', 'MM/DD/RRRR'), to_date('09/30/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (2, 'M6789', 67892, 3, 5, 'Pending', to_date('09/21/2024', 'MM/DD/RRRR'), to_date('09/26/2024', 'MM/DD/RRRR'), to_date('10/01/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (3, 'M34567', 1113, 7, 1, 'Cancelled', to_date('09/22/2024', 'MM/DD/RRRR'), to_date('09/27/2024', 'MM/DD/RRRR'), to_date('10/02/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (4, 'J45678', 13142, 4, 6, 'Confirmed', to_date('09/23/2024', 'MM/DD/RRRR'), to_date('09/28/2024', 'MM/DD/RRRR'), to_date('10/03/2024', 'MM/DD/RRRR'), to_date('11/03/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (5, 'B56789', 51618, 5, 8, 'Pending', to_date('09/24/2024', 'MM/DD/RRRR'), to_date('09/29/2024', 'MM/DD/RRRR'), to_date('10/04/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (6, 'M12345', 12347, 9, 12, 'Confirmed', to_date('09/25/2024', 'MM/DD/RRRR'), to_date('10/01/2024', 'MM/DD/RRRR'), to_date('10/05/2024', 'MM/DD/RRRR'), to_date('10/05/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (7, 'M6789', 67893, 2, 10, 'Pending', to_date('09/26/2024', 'MM/DD/RRRR'), to_date('10/02/2024', 'MM/DD/RRRR'), to_date('10/06/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (8, 'M10001', 1114, 8, 3, 'Cancelled', to_date('09/27/2024', 'MM/DD/RRRR'), to_date('10/03/2024', 'MM/DD/RRRR'), to_date('10/07/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (9, 'M10002', 51619, 11, 2, 'Confirmed', to_date('09/28/2024', 'MM/DD/RRRR'), to_date('10/04/2024', 'MM/DD/RRRR'), to_date('10/08/2024', 'MM/DD/RRRR'), to_date('10/10/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (10, 'M10003', 67894, 1, 15, 'Pending', to_date('09/29/2024', 'MM/DD/RRRR'), to_date('10/05/2024', 'MM/DD/RRRR'), to_date('10/09/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (11, 'M10004', 12348, 6, 4, 'Cancelled', to_date('09/30/2024', 'MM/DD/RRRR'), to_date('10/06/2024', 'MM/DD/RRRR'), to_date('10/10/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (12, 'M10005', 1115, 3, 7, 'Confirmed', to_date('10/01/2024', 'MM/DD/RRRR'), to_date('10/07/2024', 'MM/DD/RRRR'), to_date('10/11/2024', 'MM/DD/RRRR'), to_date('10/11/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (13, 'M10007', 13143, 12, 1, 'Pending', to_date('10/02/2024', 'MM/DD/RRRR'), to_date('10/08/2024', 'MM/DD/RRRR'), to_date('10/12/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (14, 'M10005', 51620, 15, 14, 'Cancelled', to_date('10/03/2024', 'MM/DD/RRRR'), to_date('10/09/2024', 'MM/DD/RRRR'), to_date('10/13/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (15, 'M10006', 67895, 4, 11, 'Confirmed', to_date('10/04/2024', 'MM/DD/RRRR'), to_date('10/10/2024', 'MM/DD/RRRR'), to_date('10/14/2024', 'MM/DD/RRRR'), to_date('10/14/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (16, 'M10020', 12349, 2, 9, 'Pending', to_date('10/05/2024', 'MM/DD/RRRR'), to_date('10/11/2024', 'MM/DD/RRRR'), to_date('10/15/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (17, 'M10030', 1116, 5, 8, 'Cancelled', to_date('10/06/2024', 'MM/DD/RRRR'), to_date('10/12/2024', 'MM/DD/RRRR'), to_date('10/16/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (18, 'M10031', 13144, 10, 3, 'Confirmed', to_date('10/07/2024', 'MM/DD/RRRR'), to_date('10/13/2024', 'MM/DD/RRRR'), to_date('10/17/2024', 'MM/DD/RRRR'), to_date('10/17/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (19, 'M10040', 51621, 15, 4, 'Pending', to_date('10/08/2024', 'MM/DD/RRRR'), to_date('10/14/2024', 'MM/DD/RRRR'), to_date('10/18/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (20, 'M10038', 67896, 1, 7, 'Confirmed', to_date('10/09/2024', 'MM/DD/RRRR'), to_date('10/15/2024', 'MM/DD/RRRR'), to_date('10/19/2024', 'MM/DD/RRRR'), to_date('10/21/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (21, 'M10029', 12350, 13, 5, 'Pending', to_date('10/10/2024', 'MM/DD/RRRR'), to_date('10/16/2024', 'MM/DD/RRRR'), to_date('10/20/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (22, 'M10024', 1117, 4, 2, 'Cancelled', to_date('10/11/2024', 'MM/DD/RRRR'), to_date('10/17/2024', 'MM/DD/RRRR'), to_date('10/21/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (23, 'M10022', 13145, 6, 12, 'Confirmed', to_date('10/12/2024', 'MM/DD/RRRR'), to_date('10/18/2024', 'MM/DD/RRRR'), to_date('10/22/2024', 'MM/DD/RRRR'), to_date('10/22/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (24, 'M10018', 51622, 8, 3, 'Pending', to_date('10/13/2024', 'MM/DD/RRRR'), to_date('10/19/2024', 'MM/DD/RRRR'), to_date('10/23/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (25, 'M10014', 67897, 2, 15, 'Confirmed', to_date('10/14/2024', 'MM/DD/RRRR'), to_date('10/20/2024', 'MM/DD/RRRR'), to_date('10/24/2024', 'MM/DD/RRRR'), to_date('10/24/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (26, 'M10011', 12351, 3, 11, 'Pending', to_date('10/15/2024', 'MM/DD/RRRR'), to_date('10/21/2024', 'MM/DD/RRRR'), to_date('10/25/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (27, 'M10009', 1118, 9, 1, 'Cancelled', to_date('10/16/2024', 'MM/DD/RRRR'), to_date('10/22/2024', 'MM/DD/RRRR'), to_date('10/26/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (28, 'M10007', 13146, 10, 8, 'Confirmed', to_date('10/17/2024', 'MM/DD/RRRR'), to_date('10/23/2024', 'MM/DD/RRRR'), to_date('10/27/2024', 'MM/DD/RRRR'), to_date('10/27/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (29, 'M10006', 51623, 14, 13, 'Pending', to_date('10/18/2024', 'MM/DD/RRRR'), to_date('10/24/2024', 'MM/DD/RRRR'), to_date('10/28/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (30, 'M10003', 67898, 1, 4, 'Confirmed', to_date('10/19/2024', 'MM/DD/RRRR'), to_date('10/25/2024', 'MM/DD/RRRR'), to_date('10/29/2024', 'MM/DD/RRRR'), to_date('10/29/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (31, 'M10001', 12352, 3, 6, 'Pending', to_date('10/20/2024', 'MM/DD/RRRR'), to_date('10/26/2024', 'MM/DD/RRRR'), to_date('10/30/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (32, 'M10001', 1119, 7, 2, 'Cancelled', to_date('10/21/2024', 'MM/DD/RRRR'), to_date('10/27/2024', 'MM/DD/RRRR'), to_date('10/31/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (33, 'M10001', 13147, 12, 5, 'Confirmed', to_date('10/22/2024', 'MM/DD/RRRR'), to_date('10/28/2024', 'MM/DD/RRRR'), to_date('11/01/2024', 'MM/DD/RRRR'), to_date('11/01/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (34, 'M10033', 51624, 5, 10, 'Pending', to_date('10/23/2024', 'MM/DD/RRRR'), to_date('10/29/2024', 'MM/DD/RRRR'), to_date('11/02/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (35, 'M10034', 67899, 4, 14, 'Confirmed', to_date('10/24/2024', 'MM/DD/RRRR'), to_date('10/30/2024', 'MM/DD/RRRR'), to_date('11/03/2024', 'MM/DD/RRRR'), to_date('11/03/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (36, 'M10038', 12353, 15, 9, 'Pending', to_date('10/25/2024', 'MM/DD/RRRR'), to_date('10/31/2024', 'MM/DD/RRRR'), to_date('11/04/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (37, 'M10023', 1120, 2, 7, 'Cancelled', to_date('10/26/2024', 'MM/DD/RRRR'), to_date('11/01/2024', 'MM/DD/RRRR'), to_date('11/05/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (38, 'M10028', 13148, 6, 4, 'Confirmed', to_date('10/27/2024', 'MM/DD/RRRR'), to_date('11/02/2024', 'MM/DD/RRRR'), to_date('11/06/2024', 'MM/DD/RRRR'), to_date('11/06/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (39, 'M10026', 51625, 8, 3, 'Pending', to_date('10/28/2024', 'MM/DD/RRRR'), to_date('11/03/2024', 'MM/DD/RRRR'), to_date('11/07/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (40, 'M10025', 67892, 1, 10, 'Confirmed', to_date('10/29/2024', 'MM/DD/RRRR'), to_date('11/04/2024', 'MM/DD/RRRR'), to_date('11/08/2024', 'MM/DD/RRRR'), to_date('11/08/2024', 'MM/DD/RRRR'));

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (41, 'M10001', 12353, 5, 15, 'Pending', to_date('10/30/2024', 'MM/DD/RRRR'), to_date('11/05/2024', 'MM/DD/RRRR'), to_date('11/09/2024', 'MM/DD/RRRR'), NULL);

INSERT INTO RESERVATION (RESERVATION_ID, LICENSE_NUMBER, REGISTRATION_NUMBER, PICKUP_LOCATION, RETURN_LOCATION, RENTAL_STATUS, BOOKING_DATE, START_DATE, END_DATE, RETURNED_DATE) 
VALUES (42, 'M10001', 1113, 3, 12, 'Cancelled', to_date('10/31/2024', 'MM/DD/RRRR'), to_date('11/06/2024', 'MM/DD/RRRR'), to_date('11/10/2024', 'MM/DD/RRRR'), NULL);


INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10001, 1, to_date('09/30/2024', 'MM/DD/RRRR'), 'Paid', 13, 199.99, NULL, 19.99);

INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10004, 4, to_date('11/03/2024', 'MM/DD/RRRR'), 'Paid', 12.75, 175.99, 30, 14.99);

INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10006, 6, to_date('10/05/2024', 'MM/DD/RRRR'), 'Unpaid', 10.5, 225, NULL, 15);

INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10008, 9, to_date('10/08/2024', 'MM/DD/RRRR'), 'Paid', 11.25, 190, 8, 12.5);

INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10010, 12, to_date('10/11/2024', 'MM/DD/RRRR'), 'Paid', 9.75, 210, NULL, 11);

INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10012, 15, to_date('10/14/2024', 'MM/DD/RRRR'), 'Paid', 14, 240, NULL, 20);

INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10014, 18, to_date('10/17/2024', 'MM/DD/RRRR'), 'Paid', 13.5, 180, NULL, 18);

INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10016, 20, to_date('10/21/2024', 'MM/DD/RRRR'), 'Unpaid', 12, 200, 3, 16);

INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10018, 25, to_date('10/22/2024', 'MM/DD/RRRR'), 'Paid', 11, 195, NULL, 15.5);

INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10020, 28, to_date('10/24/2024', 'MM/DD/RRRR'), 'Paid', 10, 170, NULL, 10);

INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10022, 30, to_date('10/27/2024', 'MM/DD/RRRR'), 'Paid', 11.75, 220, NULL, 17.5);

INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10024, 30, to_date('10/29/2024', 'MM/DD/RRRR'), 'Paid', 12.25, 185, NULL, 14);

INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10026, 32, to_date('11/01/2024', 'MM/DD/RRRR'), 'Paid', 12.75, 205, NULL, 15.25);

INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10028, 35, to_date('11/03/2024', 'MM/DD/RRRR'), 'Paid', 14.5, 250, NULL, 19);

INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10030, 38, to_date('11/06/2024', 'MM/DD/RRRR'), 'Paid', 13.25, 175, NULL, 13.75);

INSERT INTO BILLING (BILLING_ID, RESERVATION_ID, BILLING_DATE, BILLING_STATUS, TAX, CAR_RENTAL_FEES, CAR_LATE_FEES, PC_FEES) 
VALUES (10032, 40, to_date('11/08/2024', 'MM/DD/RRRR'), 'Unpaid', 10.5, 195.5, NULL, 11.25);


INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (1, 'Collision Damage Waiver', 20);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (2, 'Personal Accident Insurance', 10.99);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (3, 'Theft Protection', 14.99);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (4, 'Supplemental Liability', 12.99);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (5, 'Roadside Assistance', 8.99);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (6, 'Full Coverage', 35);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (7, 'Windshield Protection', 15.5);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (8, 'Personal Effects Coverage', 9.99);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (9, 'Enhanced Liability', 18);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (10, 'Loss of Use Coverage', 11.49);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (11, 'Key Replacement Coverage', 7.99);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (12, 'Accidental Death Coverage', 13.99);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (13, 'Gap Insurance', 16.5);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (14, 'Vehicle Replacement Coverage', 22);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (15, 'Emergency Medical Coverage', 19.99);

