SET DEFINE OFF

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M12345', 'Mickey', 'T.', 'Mouse', to_date('07/10/1985', 'MM/DD/YYYY'), 'Apt 101', 'Canada', 'Toronto', 'Ontario', 'M5A1A1', '213 Queen St W', 'mickey.m@gmail.com', '416-123-1111');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M6789', 'Minnie', 'E.', 'Mouse', to_date('03/22/1990', 'MM/DD/YYYY'), 'Apt 101', 'Canada', 'Toronto', 'Ontario', 'M5B2B2', '213 Queen St W', 'minnie.m@gmail.com', '416-123-2222');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M34567', 'Joanne', NULL, 'Mills', to_date('11/18/1982', 'MM/DD/YYYY'), NULL, 'Canada', 'Mississauga', 'Ontario', 'L5M3C3', '800 Lakeshore Blvd', 'jm@gmail.com', '647-321-3333');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('J45678', 'Brandon', 'J.', 'Jones', to_date('05/30/1995', 'MM/DD/YYYY'), NULL, 'Canada', 'Calgary', 'Alberta', 'T2P4P4', '180 Mountain Rd', 'b.jones@yahoo.ca', '403-555-4444');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('B56789', 'Gabriellel', 'D.', 'Brown', to_date('08/15/1987', 'MM/DD/YYYY'), 'Unit 12B', 'Canada', 'Vancouver', 'British Columbia', 'V6B5B5', '292 Country Rd', 'g.brown@gmail.com', '647-123-5282');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10001', 'Oliver', 'A.', 'Smith', to_date('01/01/1980', 'MM/DD/YYYY'), 'Apt 1', 'Canada', 'Toronto', 'Ontario', 'M5A1A2', '1 Main St', 'oliver.smith@gmail.com', '416-123-0001');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10002', 'Sophia', 'B.', 'Johnson', to_date('02/12/1985', 'MM/DD/YYYY'), 'Apt 2', 'Canada', 'Toronto', 'Ontario', 'M5A1A3', '2 Main St', 'sophia.j@gmail.com', '416-123-0002');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10003', 'Liam', 'C.', 'Williams', to_date('03/14/1992', 'MM/DD/YYYY'), 'Apt 3', 'Canada', 'Toronto', 'Ontario', 'M5A1A4', '3 Main St', 'liam.williams@gmail.com', '416-123-0003');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10004', 'Emma', 'D.', 'Jones', to_date('04/22/1988', 'MM/DD/YYYY'), 'Apt 4', 'Canada', 'Toronto', 'Ontario', 'M5A1A5', '4 Main St', 'emma.jones@gmail.com', '416-123-0004');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10005', 'Noah', 'E.', 'Garcia', to_date('05/19/1990', 'MM/DD/YYYY'), 'Apt 5', 'Canada', 'Toronto', 'Ontario', 'M5A1A6', '5 Main St', 'noah.garcia@gmail.com', '416-123-0005');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10006', 'Ava', 'F.', 'Martinez', to_date('06/11/1995', 'MM/DD/YYYY'), 'Apt 6', 'Canada', 'Toronto', 'Ontario', 'M5A1A7', '6 Main St', 'ava.martinez@gmail.com', '416-123-0006');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10007', 'Isabella', 'G.', 'Davis', to_date('07/27/1982', 'MM/DD/YYYY'), 'Apt 7', 'Canada', 'Toronto', 'Ontario', 'M5A1A8', '7 Main St', 'isabella.davis@gmail.com', '416-123-0007');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10008', 'Mason', 'H.', 'Rodriguez', to_date('08/15/1994', 'MM/DD/YYYY'), 'Apt 8', 'Canada', 'Toronto', 'Ontario', 'M5A1A9', '8 Main St', 'mason.rodriguez@gmail.com', '416-123-0008');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10009', 'James', 'I.', 'Martinez', to_date('09/09/1980', 'MM/DD/YYYY'), 'Apt 9', 'Canada', 'Toronto', 'Ontario', 'M5A1B1', '9 Main St', 'james.martinez@gmail.com', '416-123-0009');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10010', 'Charlotte', 'J.', 'Hernandez', to_date('10/14/1991', 'MM/DD/YYYY'), 'Apt 10', 'Canada', 'Toronto', 'Ontario', 'M5A1B2', '10 Main St', 'charlotte.hernandez@gmail.com', '416-123-0010');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10011', 'Elijah', 'K.', 'Lopez', to_date('11/02/1993', 'MM/DD/YYYY'), 'Apt 11', 'Canada', 'Toronto', 'Ontario', 'M5A1B3', '11 Main St', 'elijah.lopez@gmail.com', '416-123-0011');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10012', 'Amelia', 'L.', 'Gonzalez', to_date('12/29/1986', 'MM/DD/YYYY'), 'Apt 12', 'Canada', 'Toronto', 'Ontario', 'M5A1B4', '12 Main St', 'amelia.gonzalez@gmail.com', '416-123-0012');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10013', 'Benjamin', 'M.', 'Wilson', to_date('01/22/1990', 'MM/DD/YYYY'), 'Apt 13', 'Canada', 'Toronto', 'Ontario', 'M5A1B5', '13 Main St', 'benjamin.wilson@gmail.com', '416-123-0013');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10014', 'Harper', 'N.', 'Anderson', to_date('02/20/1988', 'MM/DD/YYYY'), 'Apt 14', 'Canada', 'Toronto', 'Ontario', 'M5A1B6', '14 Main St', 'harper.anderson@gmail.com', '416-123-0014');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10015', 'Lucas', 'O.', 'Thomas', to_date('03/13/1992', 'MM/DD/YYYY'), 'Apt 15', 'Canada', 'Toronto', 'Ontario', 'M5A1B7', '15 Main St', 'lucas.thomas@gmail.com', '416-123-0015');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10016', 'Evelyn', 'P.', 'Taylor', to_date('04/05/1994', 'MM/DD/YYYY'), 'Apt 16', 'Canada', 'Toronto', 'Ontario', 'M5A1B8', '16 Main St', 'evelyn.taylor@gmail.com', '416-123-0016');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10017', 'Henry', 'Q.', 'Moore', to_date('05/17/1985', 'MM/DD/YYYY'), 'Apt 17', 'Canada', 'Toronto', 'Ontario', 'M5A1B9', '17 Main St', 'henry.moore@gmail.com', '416-123-0017');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10018', 'Sofia', 'R.', 'Jackson', to_date('06/25/1996', 'MM/DD/YYYY'), 'Apt 18', 'Canada', 'Toronto', 'Ontario', 'M5A1C1', '18 Main St', 'sofia.jackson@gmail.com', '416-123-0018');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10019', 'Alexander', 'S.', 'White', to_date('07/07/1983', 'MM/DD/YYYY'), 'Apt 19', 'Canada', 'Toronto', 'Ontario', 'M5A1C2', '19 Main St', 'alexander.white@gmail.com', '416-123-0019');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10020', 'Grace', 'T.', 'Harris', to_date('08/23/1991', 'MM/DD/YYYY'), 'Apt 20', 'Canada', 'Toronto', 'Ontario', 'M5A1C3', '20 Main St', 'grace.harris@gmail.com', '416-123-0020');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10021', 'Daniel', 'U.', 'Martin', to_date('09/12/1984', 'MM/DD/YYYY'), 'Apt 21', 'Canada', 'Toronto', 'Ontario', 'M5A1C4', '21 Main St', 'daniel.martin@gmail.com', '416-123-0021');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10022', 'Lily', 'V.', 'Thompson', to_date('10/30/1990', 'MM/DD/YYYY'), 'Apt 22', 'Canada', 'Toronto', 'Ontario', 'M5A1C5', '22 Main St', 'lily.thompson@gmail.com', '416-123-0022');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10023', 'Matthew', 'W.', 'Garcia', to_date('11/11/1987', 'MM/DD/YYYY'), 'Apt 23', 'Canada', 'Toronto', 'Ontario', 'M5A1C6', '23 Main St', 'matthew.garcia@gmail.com', '416-123-0023');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10024', 'Zoe', 'X.', 'Martinez', to_date('12/09/1992', 'MM/DD/YYYY'), 'Apt 24', 'Canada', 'Toronto', 'Ontario', 'M5A1C7', '24 Main St', 'zoe.martinez@gmail.com', '416-123-0024');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10025', 'Logan', 'Y.', 'Rodriguez', to_date('01/19/1985', 'MM/DD/YYYY'), 'Apt 25', 'Canada', 'Toronto', 'Ontario', 'M5A1C8', '25 Main St', 'logan.rodriguez@gmail.com', '416-123-0025');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10026', 'Scarlett', 'Z.', 'Perez', to_date('02/25/1993', 'MM/DD/YYYY'), 'Apt 26', 'Canada', 'Toronto', 'Ontario', 'M5A1C9', '26 Main St', 'scarlett.perez@gmail.com', '416-123-0026');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10027', 'Jackson', 'A.', 'Williams', to_date('03/17/1989', 'MM/DD/YYYY'), 'Apt 27', 'Canada', 'Toronto', 'Ontario', 'M5A1D1', '27 Main St', 'jackson.williams@gmail.com', '416-123-0027');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10028', 'Aiden', 'B.', 'Anderson', to_date('04/23/1991', 'MM/DD/YYYY'), 'Apt 28', 'Canada', 'Toronto', 'Ontario', 'M5A1D2', '28 Main St', 'aiden.anderson@gmail.com', '416-123-0028');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10029', 'Evelyn', 'C.', 'Roberts', to_date('05/18/1987', 'MM/DD/YYYY'), 'Apt 29', 'Canada', 'Toronto', 'Ontario', 'M5A1D3', '29 Main St', 'evelyn.roberts@gmail.com', '416-123-0029');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10030', 'Matthew', 'D.', 'Hernandez', to_date('06/30/1994', 'MM/DD/YYYY'), 'Apt 30', 'Canada', 'Toronto', 'Ontario', 'M5A1D4', '30 Main St', 'matthew.hernandez@gmail.com', '416-123-0030');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10031', 'Chloe', 'E.', 'King', to_date('07/21/1993', 'MM/DD/YYYY'), 'Apt 31', 'Canada', 'Toronto', 'Ontario', 'M5A1D5', '31 Main St', 'chloe.king@gmail.com', '416-123-0031');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10032', 'Lucas', 'F.', 'Lee', to_date('08/12/1989', 'MM/DD/YYYY'), 'Apt 32', 'Canada', 'Toronto', 'Ontario', 'M5A1D6', '32 Main St', 'lucas.lee@gmail.com', '416-123-0032');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10033', 'Mia', 'G.', 'Walker', to_date('09/11/1991', 'MM/DD/YYYY'), 'Apt 33', 'Canada', 'Toronto', 'Ontario', 'M5A1D7', '33 Main St', 'mia.walker@gmail.com', '416-123-0033');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10034', 'Noah', 'H.', 'Hall', to_date('10/16/1992', 'MM/DD/YYYY'), 'Apt 34', 'Canada', 'Toronto', 'Ontario', 'M5A1D8', '34 Main St', 'noah.hall@gmail.com', '416-123-0034');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10035', 'Isabella', 'I.', 'Young', to_date('11/20/1996', 'MM/DD/YYYY'), 'Apt 35', 'Canada', 'Toronto', 'Ontario', 'M5A1D9', '35 Main St', 'isabella.young@gmail.com', '416-123-0035');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10036', 'Oliver', 'J.', 'Wright', to_date('12/27/1985', 'MM/DD/YYYY'), 'Apt 36', 'Canada', 'Toronto', 'Ontario', 'M5A1E1', '36 Main St', 'oliver.wright@gmail.com', '416-123-0036');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10037', 'Sofia', 'K.', 'Scott', to_date('01/18/1990', 'MM/DD/YYYY'), 'Apt 37', 'Canada', 'Toronto', 'Ontario', 'M5A1E2', '37 Main St', 'sofia.scott@gmail.com', '416-123-0037');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10038', 'Elijah', 'L.', 'Green', to_date('02/24/1989', 'MM/DD/YYYY'), 'Apt 38', 'Canada', 'Toronto', 'Ontario', 'M5A1E3', '38 Main St', 'elijah.green@gmail.com', '416-123-0038');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10039', 'Amelia', 'M.', 'Adams', to_date('03/09/1991', 'MM/DD/YYYY'), 'Apt 39', 'Canada', 'Toronto', 'Ontario', 'M5A1E4', '39 Main St', 'amelia.adams@gmail.com', '416-123-0039');

INSERT INTO CUSTOMER (LICENSE_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, DATE_OF_BIRTH, APARTMENT, COUNTRY, CITY, PROVINCE, POSTAL_CODE, STREET_ADDRESS, EMAIL_ADDRESS, PHONE_NUMBER) 
VALUES ('M10040', 'Benjamin', 'N.', 'Baker', to_date('04/02/1988', 'MM/DD/YYYY'), 'Apt 40', 'Canada', 'Toronto', 'Ontario', 'M5A1E5', '40 Main St', 'benjamin.baker@gmail.com', '416-123-0040');

