SET DEFINE OFF

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2001, 1, 'Alan', 'B.', 'Richards', 55000, 'Manager', to_date('02/17/1985', 'MM/DD/RRRR'), '416-555-1212', 'alan.richards@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2002, 2, 'Samantha', 'C.', 'Blake', 45000, 'Janitor', to_date('07/25/1990', 'MM/DD/RRRR'), '416-555-2323', 'samantha.blake@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2003, 3, 'Peter', 'D.', 'Jones', 60000, 'Manager', to_date('12/10/1983', 'MM/DD/RRRR'), '416-555-3434', 'peter.jones@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2004, 4, 'Jessica', 'E.', 'Roberts', 52000, 'Assistant', to_date('04/04/1995', 'MM/DD/RRRR'), '403-555-4545', 'jessica.roberts@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2005, 5, 'Ryan', 'F.', 'Stewart', 48000, 'Salesperson', to_date('04/04/1995', 'MM/DD/RRRR'), '403-555-4545', 'ryan.stewart@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2006, 1, 'Daniel', 'A.', 'Smith', 60000, 'Manager', to_date('01/15/1988', 'MM/DD/RRRR'), '416-555-1616', 'daniel.smith@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2007, 2, 'Emily', 'B.', 'Johnson', 38000, 'Janitor', to_date('03/22/1995', 'MM/DD/RRRR'), '416-555-1717', 'emily.johnson@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2008, 3, 'Matthew', 'C.', 'Williams', 55000, 'Manager', to_date('05/30/1984', 'MM/DD/RRRR'), '416-555-1818', 'matthew.williams@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2009, 4, 'Olivia', 'D.', 'Jones', 49000, 'Assistant', to_date('07/14/1992', 'MM/DD/RRRR'), '403-555-1919', 'olivia.jones@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2010, 5, 'Lucas', 'E.', 'Brown', 45000, 'Salesperson', to_date('08/19/1989', 'MM/DD/RRRR'), '403-555-2020', 'lucas.brown@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2011, 1, 'Sophia', 'F.', 'Davis', 67000, 'Manager', to_date('12/01/1990', 'MM/DD/RRRR'), '416-555-2121', 'sophia.davis@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2012, 2, 'James', 'G.', 'Miller', 42000, 'Janitor', to_date('06/05/1996', 'MM/DD/RRRR'), '416-555-2222', 'james.miller@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2013, 3, 'Ava', 'H.', 'Garcia', 63000, 'Manager', to_date('11/25/1982', 'MM/DD/RRRR'), '416-555-2323', 'ava.garcia@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2014, 4, 'Charlotte', 'I.', 'Martinez', 52000, 'Assistant', to_date('09/15/1993', 'MM/DD/RRRR'), '403-555-2424', 'charlotte.martinez@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2015, 5, 'Noah', 'J.', 'Hernandez', 46000, 'Salesperson', to_date('02/27/1985', 'MM/DD/RRRR'), '403-555-2525', 'noah.hernandez@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2016, 1, 'Amelia', 'K.', 'Lopez', 58000, 'Manager', to_date('04/18/1981', 'MM/DD/RRRR'), '416-555-2626', 'amelia.lopez@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2017, 2, 'Elijah', 'L.', 'Gonzalez', 37000, 'Janitor', to_date('08/22/1998', 'MM/DD/RRRR'), '416-555-2727', 'elijah.gonzalez@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2018, 3, 'Harper', 'M.', 'Wilson', 59000, 'Manager', to_date('03/16/1986', 'MM/DD/RRRR'), '416-555-2828', 'harper.wilson@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2019, 4, 'Jack', 'N.', 'Anderson', 50000, 'Assistant', to_date('05/05/1994', 'MM/DD/RRRR'), '403-555-2929', 'jack.anderson@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2020, 5, 'Grace', 'O.', 'Thomas', 48000, 'Salesperson', to_date('11/12/1990', 'MM/DD/RRRR'), '403-555-3030', 'grace.thomas@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2021, 1, 'Ethan', 'P.', 'Taylor', 64000, 'Manager', to_date('12/30/1987', 'MM/DD/RRRR'), '416-555-3131', 'ethan.taylor@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2022, 2, 'Chloe', 'Q.', 'Moore', 43000, 'Janitor', to_date('02/24/1999', 'MM/DD/RRRR'), '416-555-3232', 'chloe.moore@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2023, 3, 'Mason', 'R.', 'Jackson', 61000, 'Manager', to_date('07/19/1983', 'MM/DD/RRRR'), '416-555-3333', 'mason.jackson@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2024, 4, 'Zoe', 'S.', 'Martin', 52000, 'Assistant', to_date('01/10/1992', 'MM/DD/RRRR'), '403-555-3434', 'zoe.martin@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2025, 5, 'Liam', 'T.', 'Lee', 46000, 'Salesperson', to_date('04/28/1989', 'MM/DD/RRRR'), '403-555-3535', 'liam.lee@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2026, 1, 'Lily', 'U.', 'Perez', 60000, 'Manager', to_date('05/02/1984', 'MM/DD/RRRR'), '416-555-3636', 'lily.perez@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2027, 2, 'Alexander', 'V.', 'Thompson', 38000, 'Janitor', to_date('09/15/1996', 'MM/DD/RRRR'), '416-555-3737', 'alexander.thompson@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2028, 3, 'Sofia', 'W.', 'White', 67000, 'Manager', to_date('08/08/1982', 'MM/DD/RRRR'), '416-555-3838', 'sofia.white@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2029, 4, 'Matthew', 'X.', 'Harris', 53000, 'Assistant', to_date('03/20/1990', 'MM/DD/RRRR'), '403-555-3939', 'matthew.harris@driveease.com');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, LOCATION_NUMBER, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SALARY, POSITION, DATE_OF_BIRTH, PHONE_NUMBER, EMAIL_ADDRESS) 
VALUES (2030, 5, 'Victoria', 'Y.', 'Clark', 48000, 'Salesperson', to_date('11/23/1986', 'MM/DD/RRRR'), '403-555-4040', 'victoria.clark@driveease.com');

