SET DEFINE OFF

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (1, 2020, 'Corolla', 'Toyota', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (2, 2021, 'Civic', 'Honda', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (3, 2022, 'Model 3', 'Tesla', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (4, 2019, 'Mustang', 'Ford', 4);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (5, 2020, 'Cherokee', 'Jeep', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (6, 2018, 'Accord', 'Honda', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (7, 2020, 'Camry', 'Toyota', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (8, 2019, 'Rav4', 'Toyota', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (9, 2022, 'Escape', 'Ford', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (10, 2021, 'Explorer', 'Ford', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (11, 2020, 'Altima', 'Nissan', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (12, 2023, 'Sentra', 'Nissan', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (13, 2021, 'Santa Fe', 'Hyundai', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (14, 2022, 'Tucson', 'Hyundai', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (15, 2020, 'Sorento', 'Kia', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (16, 2021, 'Sportage', 'Kia', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (17, 2019, 'Optima', 'Kia', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (18, 2022, 'Highlander', 'Toyota', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (19, 2023, 'Pathfinder', 'Nissan', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (20, 2020, 'Suburban', 'Chevrolet', 8);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (21, 2021, 'Tahoe', 'Chevrolet', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (22, 2022, 'Impala', 'Chevrolet', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (23, 2018, 'Malibu', 'Chevrolet', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (24, 2023, 'Fusion', 'Ford', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (25, 2021, 'Mazda3', 'Mazda', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (26, 2019, 'Mazda6', 'Mazda', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (27, 2022, 'CX-5', 'Mazda', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (28, 2023, 'CX-9', 'Mazda', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (29, 2020, 'Forester', 'Subaru', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (30, 2021, 'Outback', 'Subaru', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (31, 2022, 'Ascent', 'Subaru', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (32, 2019, 'Wrangler', 'Jeep', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (33, 2020, 'Compass', 'Jeep', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (34, 2021, 'Gladiator', 'Jeep', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (35, 2022, 'Telluride', 'Kia', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (36, 2023, 'Palisade', 'Hyundai', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (37, 2020, 'Atlas', 'Volkswagen', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (38, 2021, 'Tiguan', 'Volkswagen', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (39, 2022, 'Passat', 'Volkswagen', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (40, 2023, 'Jetta', 'Volkswagen', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (41, 2019, 'S-Class', 'Mercedes-Benz', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (42, 2020, 'E-Class', 'Mercedes-Benz', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (43, 2021, 'C-Class', 'Mercedes-Benz', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (44, 2022, 'A4', 'Audi', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (45, 2023, 'Q7', 'Audi', 7);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (46, 2018, 'Q5', 'Audi', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (47, 2020, 'A6', 'Audi', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (48, 2021, 'Q3', 'Audi', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (49, 2022, 'Range Rover', 'Land Rover', 5);

INSERT INTO MODEL (MODEL_NUMBER, MODEL_YEAR, MODEL_NAME, MANUFACTURER, NUMBER_OF_SEATS) 
VALUES (50, 2023, 'Defender', 'Land Rover', 5);

