SET DEFINE OFF

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (1, 'Collision Damage Waiver', 20);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (2, 'Personal Accident Insurance', 10.99);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (3, 'Theft Protection', 14.99);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (4, 'Supplemental Liability', 12.99);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (5, 'Roadside Assistance', 8.99);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (6, 'Full Coverage', 35);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (7, 'Windshield Protection', 15.5);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (8, 'Personal Effects Coverage', 9.99);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (9, 'Enhanced Liability', 18);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (10, 'Loss of Use Coverage', 11.49);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (11, 'Key Replacement Coverage', 7.99);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (12, 'Accidental Death Coverage', 13.99);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (13, 'Gap Insurance', 16.5);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (14, 'Vehicle Replacement Coverage', 22);

INSERT INTO PROTECTIONS_COVERAGES (PC_CODE, PC_NAME, PC_PRICE) 
VALUES (15, 'Emergency Medical Coverage', 19.99);

